CREATE TABLE fcm(
    id INT PRIMARY KEY UNIQUE AUTO_INCREMENT NOT NULL,
    token VARCHAR(255) NOT NULL,
    user INT NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user) REFERENCES user(id)
);
