CREATE TABLE IF NOT EXISTS chatroom(
    id INT PRIMARY KEY UNIQUE NOT NULL AUTO_INCREMENT,
    user1 INT NOT NULL,
    user2 INT NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted TIMESTAMP,
    FOREIGN KEY (user1) REFERENCES user(id),
    FOREIGN KEY (user2) REFERENCES user(id)
);

CREATE TABLE IF NOT EXISTS message (
    id INT PRIMARY KEY UNIQUE NOT NULL AUTO_INCREMENT,
    chatroom_id INT NOT NULL,
    sender_id INT NOT NULL,
    content TEXT NOT NULL,
    delivered BOOLEAN DEFAULT FALSE,
    isread BOOLEAN DEFAULT FALSE,
    sent TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (chatroom_id) REFERENCES chatroom(id),
    FOREIGN KEY (sender_id) REFERENCES user(id)
);